services:
  - type: web
    name: customer-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: GOOGLE_CREDENTIALS
        sync: false
